on:
  push:
  pull_request:

name: Checks

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CARGO_PROFILE_DEV_DEBUG: '0' # reduce size of target directory

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: star
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy, rustfmt
          toolchain: 1.71
          override: true

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Install diesel
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force diesel_cli

      - name: Run db migration
        run: diesel migration run
        env:
          DATABASE_URL: "postgres://star:password@localhost:5432/postgres"
      - name: Build/Test
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          TEST_DATABASE_URL: "postgres://star:password@localhost:5432/postgres"

      - name: Test Client Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --manifest-path misc/test-client/Cargo.toml

      - name: Test Client Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-targets --manifest-path misc/test-client/Cargo.toml
